### ISSUE TITLE
Feed

### ISSUE THREAD

**Issue by javiermortiz** [JSchutza/Good_Pods#22]
Hi team, good job so far! Here are some comments about the feed:

- [x] add  justify-content: space-between for the div.genre_div that is holding the podcasts
- [x] Add some margin between a category box and the next category box. 
- [x] I would limit each category box to display only 3 podcasts. You can have a show page for each categories if the user wants to see all the podcasts for that genre. That will ensure that every category box in the feed looks the same. 
- [x] You might want to make the entire column for the podcast an anchor tag so that when the user clicks anywhere in the podcasts they get redirected to the podcast show page.
- [x] Add some margin between "The Feed" title and the navbar.
- [x] Not sure what add stuff is next to average rating, but I think that it makes sense to give the full width of the column to the rating and move the add stuff to the following line. But that might be just me without sufficient context of add stuff.
- [x] The browse by genre menu: give the user a more clear idea that the it is a menu. Maybe make the div darker on hover or highlight the anchor tag on hover.

Good job!

**Comment by cpbeachler** [comment]
All bullet points have been reviewed and updated! Thanks Javier!
