### ISSUE TITLE
User auth

### ISSUE THREAD

**Issue by javiermortiz** [JSchutza/Good_Pods#8]
Hi team! good job so far! Here are some comments on user auth:

- [x] The Welcome to Podemic! needs some margin with the header and the sign up form.
- [x] If I sign up with empty fields, I get redirected to /me that displays the errors but it has 0 styling. The errors should be rendered in the same sign up form and should be styled.
- [x] The login form should have some margin with the Podemic header.
- [x] When I submit login form with empty fields I get a "cannot read property 'hashedPassword' of null. The errors should be rendered in the same form and they need to be something that user will understand.
- [x] Add a demo login

**Comment by JSchutza** [comment]
All fixed.
